// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function AddPluginOU() {
    return $Call.ByID(1471480547);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<string>}
 */
export function Analyze(url) {
    return $Call.ByID(3128392375, url);
}

/**
 * @param {string} v
 * @returns {$CancellablePromise<string>}
 */
export function BSEncoder(v) {
    return $Call.ByID(1644188514, v);
}

/**
 * @param {string} d
 * @returns {$CancellablePromise<void>}
 */
export function Copy(d) {
    return $Call.ByID(1489434416, d);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTs() {
    return $Call.ByID(2222600071);
}

/**
 * @returns {$CancellablePromise<$models.Config>}
 */
export function GetConfig() {
    return $Call.ByID(1866658905).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * P.T
 * @returns {$CancellablePromise<string[]>}
 */
export function GetPluginListOU() {
    return $Call.ByID(3562274576).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetPort() {
    return $Call.ByID(450544820);
}

/**
 * @returns {$CancellablePromise<$models.DownloadLib[]>}
 */
export function LibLoad() {
    return $Call.ByID(4114757468).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenFolder(path) {
    return $Call.ByID(3465823853, path);
}

/**
 * @param {string} url
 * @param {boolean} t
 * @param {boolean} s
 * @returns {$CancellablePromise<void>}
 */
export function OpenURL(url, t, s) {
    return $Call.ByID(1573416558, url, t, s);
}

/**
 * @param {string} a
 * @param {{ [_ in string]?: any }} b
 * @returns {$CancellablePromise<void>}
 */
export function RunPluginOU(a, b) {
    return $Call.ByID(1872798781, a, b);
}

/**
 * @param {string} finalM3u8UrlT
 * @param {string} bTypeT
 * @returns {$CancellablePromise<$models.Dst>}
 */
export function Start(finalM3u8UrlT, bTypeT) {
    return $Call.ByID(1372781387, finalM3u8UrlT, bTypeT).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopAll() {
    return $Call.ByID(2142450656);
}

/**
 * @param {string} d
 * @returns {$CancellablePromise<string>}
 */
export function TestGsi(d) {
    return $Call.ByID(2762071502, d);
}

/**
 * @param {string} g_asa
 * @param {number} g_bs
 * @param {number} g_ms
 * @param {boolean} g_la
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConfig(g_asa, g_bs, g_ms, g_la) {
    return $Call.ByID(2182676582, g_asa, g_bs, g_ms, g_la);
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $models.DownloadLib.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.Dst.createFrom;
