// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("appScriptKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appScriptKey"] = "";
        }
        if (!("batchSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["batchSize"] = 0;
        }
        if (!("maxSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxSize"] = 0;
        }
        if (!("downloadMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadMode"] = "";
        }
        if (!("lowLatency" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["lowLatency"] = false;
        }
        if (!("watchPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["watchPort"] = 0;
        }
        if (!("ffmpegPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ffmpegPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class DownloadLib {
    /**
     * Creates a new DownloadLib instance.
     * @param {Partial<DownloadLib>} [$$source = {}] - The source object to create the DownloadLib.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadLib instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadLib}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadLib(/** @type {Partial<DownloadLib>} */($$parsedSource));
    }
}

export class Dst {
    /**
     * Creates a new Dst instance.
     * @param {Partial<Dst>} [$$source = {}] - The source object to create the Dst.
     */
    constructor($$source = {}) {
        if (!("dlib" in $$source)) {
            /**
             * @member
             * @type {DownloadLib}
             */
            this["dlib"] = (new DownloadLib());
        }
        if (!("dtl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dtl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Dst instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Dst}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dlib" in $$parsedSource) {
            $$parsedSource["dlib"] = $$createField0_0($$parsedSource["dlib"]);
        }
        return new Dst(/** @type {Partial<Dst>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = DownloadLib.createFrom;
